upload_max_filesize = 256M
post_max_size = 256M
max_execution_time = 1000
max_input_time = 1000
memory_limit = 1024M
date.timezone = UTC
display_errors = On
display_startup_errors = On
error_reporting = E_ALL & ~E_NOTICE & ~E_STRICT & ~E_DEPRECATED
log_errors = 1
error_log = "/var/log/php/error.log"
